bcnmy/nexus

contracts/utils/RegistryBootstrap.sol
**Issue**: In the `Bootstrap` contract, the registry is never called as modules are installed before calling `_configureRegistry()`, violating the EIP-7484 spec.
**Fix**: Called `_configureRegistry()` before installing modules to ensure the registry is queried as required.
**Summary of Fixes**:
- Adjusted the order of operations in the `Bootstrap` contract functions to call `_configureRegistry()` before installing modules, ensuring compliance with EIP-7484.
=> 🔒 H-03 - Enforce Registry Calls Before Module Setup to Comply with EIP-7484

contracts/factory/BiconomyMetaFactory.sol, contracts/factory/K1ValidatorFactory.sol, contracts/factory/NexusAccountFactory.sol, contracts/factory/RegistryFactory.sol, contracts/interfaces/factory/INexusFactory.sol, contracts/utils/RegistryBootstrap.sol, test/foundry/unit/concrete/factory/TestK1ValidatorFactory_Deployments.t.sol
**Issue**: When a user tries to create a Nexus account that has already been deployed, the initial ETH deposit gets stuck in the factory contract. This can be exploited by attackers to perform griefing attacks.
**Fix**: Introduced a new error `AccountAlreadyDeployed` that reverts the tx if the account is already deployed and `msg.value` > 0.
**Summary of Fixes**:
- Introduced the `AccountAlreadyDeployed` error.
- Updated factory contracts to revert with `AccountAlreadyDeployed` when the account is already deployed and `msg.value` > 0.
=> 🔒 H-02 - Prevent Freezing of Funds in Factory Contracts

contracts/Nexus.sol, contracts/base/ModuleManager.sol, contracts/factory/BiconomyMetaFactory.sol, contracts/factory/K1ValidatorFactory.sol, contracts/factory/NexusAccountFactory.sol, contracts/factory/RegistryFactory.sol, contracts/interfaces/factory/INexusFactory.sol, contracts/utils/RegistryBootstrap.sol, test/foundry/unit/concrete/factory/TestK1ValidatorFactory_Deployments.t.sol
**Issue**: Users may lose funds because `msg.value` is ignored during the creation of a Nexus account or execution of user ops. Any ETH sent with these txs could be lost if not properly handled.
**Fix**: Added handling for `msg.value` to ensure any ETH sent with the tx is forwarded appropriately.
**Summary of Fixes**:
- Added handling for `msg.value` in the `deployWithFactory`, `executeUserOp`, and `fallback` functions to ensure ETH is properly forwarded.
=> 🔒 H-01 - Ensure msg.value is Forwarded to Prevent Loss of User Funds

contracts/base/BaseAccount.sol, contracts/interfaces/factory/INexusFactory.sol, test/foundry/utils/EventsAndErrors.sol
- **Issue**: `indexed` keyword causes data loss for `bytes` variables in events.
- **Affected Events**: `AccountCreated` in `NexusAccountFactory`.
- **Fix**: Remove `indexed` keyword from `bytes` variables in events.
---
- **Issue**: `entryPoint()` function lacks the `virtual` keyword.
- **Affected Functions**: `entryPoint`.
- **Fix**: Add `virtual` keyword to `entryPoint()` function.
---
=> 🔒 L-01 & L-02 - Prevent Data Loss in Events and Allow Overriding of entryPoint() Function

contracts/Nexus.sol, contracts/base/ModuleManager.sol, test/foundry/unit/concrete/modulemanager/TestModuleManager_EnableMode.t.sol, test/foundry/unit/concrete/modulemanager/TestModuleManager_EnableMode.tree
- Ensures proper validation of module type during enable mode in `validateUserOp`.
- Adds a check to confirm the module type is a validator.
- Prevents bypassing validation by non-validator module types.
=> Fix Finding #19: Ensure Validator Module Type Check in Enable Mode

contracts/base/ExecutionHelper.sol, contracts/base/ModuleManager.sol, test/foundry/unit/concrete/accountexecution/TestAccountExecution_TryExecuteBatch.t.sol, test/foundry/unit/concrete/accountexecution/TestAccountExecution_TryExecuteSingle.t.sol, test/foundry/unit/concrete/accountexecution/TestAccountExecution_TryExecuteSingle.tree, test/foundry/unit/concrete/modulemanager/TestModuleManager_EnableMode.t.sol, test/foundry/unit/concrete/modulemanager/TestModuleManager_EnableMode.tree, test/foundry/utils/EventsAndErrors.sol, test/hardhat/smart-account/Nexus.Basics.specs.ts
**Description:**
- When calling `execute()` with `EXECTYPE_TRY` and either `CALLTYPE_SINGLE` or `CALLTYPE_DELEGATECALL`, no event is emitted if the try fails.
- With `CALLTYPE_BATCH`, the `TryExecuteUnsuccessful` event is emitted for each failure.
- In `executeFromExecutor`, `TryDelegateCallUnsuccessful` and `TryExecuteUnsuccessful` events are emitted appropriately.
=> Fix/finding #21 - Emit Events for Failed Try Execution in `execute`

contracts/Nexus.sol, contracts/base/ModuleManager.sol
have used try catch
but could also have done it like this
(bool success, ) = hook.call(abi.encodeWithSelector(IModule.onUninstall.selector, data));
if (!success) {
// leave this block empty to ignore the revert
}
=> fix finding 41 - modules can prevent from uninstalling themselves

contracts/base/ModuleManager.sol, contracts/interfaces/base/IModuleManagerEventsAndErrors.sol, test/foundry/integration/UpgradeSmartAccountTest.t.sol, test/foundry/unit/concrete/fallback/TestNexus_FallbackFunction.t.sol, test/foundry/unit/fuzz/TestFuzz_ModuleManager.t.sol, test/foundry/utils/EventsAndErrors.sol
+ review dev notes on tests
removed receiver base and receiverFallback modifier
Hooking fallback now ( I think we can remove all blacklisted all together from installFallback @filmakarov )
added receiver function
(for now) not throwing on unfound selector [ check comments [here](https://cantina.xyz/code/d1d4b139-9705-4367-9468-297b7078674e/findings/13) ] 
running the code for token callbacks at the end.
left a room and dev notes for throwing in case of unregistered selector and unsupported calltype.
=> hooking fallback + remove receiver base + disallow bytes4(0) selector

contracts/factory/K1ValidatorFactory.sol, contracts/factory/NexusAccountFactory.sol, contracts/factory/RegistryFactory.sol, test/foundry/unit/concrete/factory/TestAccountFactory_Deployments.t.sol, test/foundry/unit/concrete/factory/TestAccountFactory_Deployments.tree, test/foundry/unit/concrete/factory/TestK1ValidatorFactory_Deployments.t.sol, test/foundry/unit/concrete/factory/TestK1ValidatorFactory_Deployments.tree, test/foundry/unit/concrete/factory/TestNexusAccountFactory_Deployments.t.sol, test/foundry/unit/concrete/factory/TestRegistryFactory_Deployments.t.sol
This PR addresses security audit finding #2 regarding non-deterministic salt computation in the `createAccount` function across several factory contracts. The following updates were made:
- **K1ValidatorFactory**: 
- Updated NatSpec documentation.
- Fixed non-deterministic salt issue by ensuring all parameters are correctly hashed together.
- **NexusAccountFactory**:
- Rewritten assembly code for correct salt computation.
- Added missing NatSpec documentation.
- **RegistryFactory**:
- Corrected assembly code for deterministic salt computation.
- Optimized gas usage by changing `isModuleAllowed` from public to private.
- **Test Cases**:
- Added tests to verify that manually computed addresses match those generated by the updated `computeAccountAddress` function, ensuring the correctness of …
=> Fix/finding #2 Fix Calculating Salt

contracts/Nexus.sol
msgSender field that the hook sees
one major upside of delegatecalling to the account only is that existing hooks will be more easily compatible
eg a spending limit hook will decode the execute calldata and check for the function signature but in the case of using the executeUserOp func on nexus the calldata could be address(erc20), transfer(...) in which case hooks also need to be able to decode this
If you instead have the account delegatecall to eg execute, then the hook can just decode normally
there are no real downsides to delegatecall here
=> update executeUserOp implementation

contracts/Nexus.sol
" I mean, since executeUserOp can delegatecall now, can we make execute to be onlyEntryPoint ?  
It will make execute->execute impossible. so the flow is more deterministic.  
otherwise it will be possible to trick user to create some execute->execute permission and bypass some limits with sessions "
=> feat: make execute function onlyEntryPoint

contracts/Nexus.sol, contracts/interfaces/INexusEventsAndErrors.sol, contracts/interfaces/base/IStorage.sol, test/foundry/unit/concrete/hook/TestNexus_Hook_Emergency_Uninstall.sol, test/foundry/utils/EventsAndErrors.sol
please refer to description and comments on
https://github.com/bcnmy/nexus/pull/150
=> feat: add hook emergency uninstall

contracts/base/ModuleManager.sol
Two new modifiers have been introduced to ModuleManager contract : onlyValidatorModule() and onlyAuthorized().
These are not used in the current codebase and the team clarified that there was no intention to use them in near future.
=> fix: remove unnecessary code

contracts/Nexus.sol, test/foundry/unit/concrete/hook/TestNexus_Hook_Emergency_Uninstall.sol, test/foundry/utils/EventsAndErrors.sol
**Problem:**
The emergencyUninstallHook() function is meant to allow the account owner to remove a hook from the account (minus the pre and post checks on the hook).
It is an alternate to the uninstallModule() function which offers hook checks on calls to uninstall any type of modules.
A timelock has been placed to only allow the account to emergency-uninstall the hook after 1 day of placing an uninstall request. But emergencyUninstallHook() fails to check that the hook was actually installed.
This allows the timelock to be bypassed through the following steps :
Call emergencyUninstallHook() to place an uninstall request even before installing the hook => this records a timestamp corresponding to the hook address
After nearly a day has passed, install the hook and use it
Immediately call …
=> fix: check if hook installed before emergency uninstall

contracts/Nexus.sol
The hook is called multiple times when the external installModule function is called.
**Fix:**
The internal function requires the modifier as _installModule is called from more than one places.
Remove from the external function with a natspec comment explaining that the modifier is applied to the internal function. Include a second natspec comment on the internal function to indicate that it should not be removed.
=> refactor: remove duplicate modifier

package.json, yarn.lock
noticed this in sdk
GET https://api.github.com/repos/OpenZeppelin/openzeppelin-contracts//tarball/ - 404
=> refactor: openzeppelin dep

contracts/modules/validators/K1Validator.sol
based on
https://github.com/bcnmy/nexus/pull/198/files#r1790412333
=> fix: k1 validator 0 address check

contracts/modules/validators/K1Validator.sol, test/foundry/unit/concrete/modules/TestK1Validator.t.sol, test/foundry/unit/concrete/modules/TestK1Validator.tree
Moved sig malleability protection to 1271 flow only as for erc4337 it is excess
1) ERC-4337 flow has nonce protection against replays including signature malleability. So there is no need to apply this check
2) ERC-1271 flow has no in-built protection against replays including signature malleability. 
Even reference implementation includes the 's' check: https://eips.ethereum.org/EIPS/eip-1271#reference-implementation
If one is using OZ's ECDSA, this above check is applied under the hood : https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L134-L145
However, in our K1Validator we use Solady ECDSA.tryRecover 
https://github.com/bcnmy/nexus/blob/69f437bb5db46e60c62bb780fcebc4120cab130a/contracts/modules/validators/K1Validator.sol#L15 …
=> Sig malleability protection for erc1271 only

contracts/lib/ExecLib.sol
As per communication with Spearbit it was decided to remove the check
1) Nor me neither auditors were able to figure out the PoC to exploit this
2) Solady doesn't have this check in their lib: [link](https://github.com/Vectorized/solady/blob/ceb1019a774a04c2ee1a283d3db5a3dfcb7ab8c2/src/accounts/LibERC7579.sol#L185-L199)
3) The check was inaccurate anyways (executions.length returns struct array length, not bytes array length)
=> Revert to last audited commit (9f1c23f6)

contracts/Nexus.sol, contracts/base/ModuleManager.sol, contracts/interfaces/INexusEventsAndErrors.sol, contracts/interfaces/base/IStorage.sol, contracts/lib/Initializable.sol, contracts/lib/NexusSentinelList.sol, contracts/mocks/ExposedNexus.sol, test/foundry/unit/concrete/eip7702/TestEIP7702.t.sol, test/foundry/unit/concrete/factory/TestAccountFactory_Deployments.t.sol, test/foundry/unit/concrete/factory/TestNexusAccountFactory_Deployments.t.sol, test/foundry/unit/concrete/nexus-sentinel-list/NexusSentinelListLib_Test.t.sol, test/foundry/unit/fuzz/TestFuzz_ModuleManager.t.sol, test/foundry/utils/EventsAndErrors.sol, test/foundry/utils/Imports.sol
- Check that the 7702 auth hash was signed by address this
- Check that `r` value of the auth signature contains hash of the `initData`
- Check that `s` value of the auth signature matches the pattern (20 MSB are 0s)
- Introduces custom SentinelList library that stores info about is this a Nick's method Nexus or not. It is done to not use a separate SSTORE at initialization, but using some already used slot. 
**! Needs extensive testing, especially for the Nick's method initialization flow**
=> Add Nick's method support on initialization
